In [6]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler, StandardScaler, MaxAbsScaler

In [10]:
df = {
    'age': [25, 30, 35, 40, 45],
    'income': [50000, 60000, 70000, 800, 90000],
    'height': [160, 165, 170, 175, 180]
}

df = pd.DataFrame(df)
df.head()

   age  income  height
0   25   50000     160
1   30   60000     165
2   35   70000     170
3   40     800     175
4   45   90000     180

In [11]:
scaler  = StandardScaler()

data = scaler.fit_transform(df)
data

scaled_df = pd.DataFrame(data, columns=df.columns)
scaled_df.head()

        age    income    height
0 -1.414214 -0.139693 -1.414214
1 -0.707107  0.196108 -0.707107
2  0.000000  0.531908  0.000000
3  0.707107 -1.791833  0.707107
4  1.414214  1.203510  1.414214

In [12]:
scaler  = MinMaxScaler()

data = scaler.fit_transform(df)
data

scaled_df = pd.DataFrame(data, columns=df.columns)
scaled_df.head()

    age    income  height
0  0.00  0.551570    0.00
1  0.25  0.663677    0.25
2  0.50  0.775785    0.50
3  0.75  0.000000    0.75
4  1.00  1.000000    1.00